version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["sh", "./start.sh"]
    environment:
      - DATABASE_URL=postgres://postgres:projectOne@db:5432/postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: projectOne
    ports:
      - "5433:5433"
