# Generated by Django 5.0.6 on 2024-06-25 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_management', '0002_alter_inventorymanagement_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Management',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('unit_sold_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='inventory_management.inventorymanagement')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
