# Generated by Django 5.0.6 on 2024-06-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventorymanagement',
            table='inventory_management',
        ),
    ]
